name: Terraform deployment
on:
  push:
    branches: [ "master" ]

jobs:
  deploy-artifact-registry:
      runs-on: ubuntu-latest
    
      steps:
        - name: Checkout the repository to the runner
          uses: actions/checkout@v2
    
        - name: Setup Terraform with specified version on the runner
          uses: hashicorp/setup-terraform@v2
        
        - name: auth to google
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
        
        - name: terraform init
          working-directory: terraform/artifact_registry
          run: | 
            terraform init -input=false
            terraform validate
        - name: terraform plan
          working-directory: terraform/artifact_registry
          id: plan
          run: terraform plan -out=plan.tfplan -input=false
          continue-on-error: true 
        - name: terraform apply
          working-directory: terraform/artifact_registry
          if: steps.plan.outcome == 'failure' 
          run: terraform apply -input=false -auto-approve plan.tfplan
  
  deploy-docker-to-registry:
      needs: deploy-artifact-registry
      runs-on: ubuntu-latest
      if: (contains(github.event.head_commit.modified, 'dockerfile') || contains(github.event.head_commit.modified, 'requirements.txt') || contains(github.event.head_commit.modified, 'app/'))

      steps:
        - name: Checkout the repository to the runner
          uses: actions/checkout@v2
        
        - name: auth to google
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
        
        - name: auth to google docker
          run: gcloud auth configure-docker us-central1-docker.pkg.dev --project silicon-garage-438603-m6
    
        - name: Build the Docker image
          run: docker build . --file dockerfile --tag us-central1-docker.pkg.dev/silicon-garage-438603-m6/mycloudrun-registry-docker/model_api:latest
        
        - name: Run shell script
          run: docker push us-central1-docker.pkg.dev/silicon-garage-438603-m6/mycloudrun-registry-docker/model_api:latest
  deploy-bq-and-pubsub:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2
  
      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
      
      - name: auth to google
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      
      - name: terraform init
        working-directory: terraform/bigquery
        run: | 
          terraform init -input=false
          terraform validate
      - name: terraform plan
        working-directory: terraform/bigquery
        id: plan
        run: terraform plan -out=plan.tfplan -input=false
        continue-on-error: true 
      - name: terraform apply
        working-directory: terraform/bigquery
        if: steps.plan.outcome == 'failure' 
        run: terraform apply -input=false -auto-approve plan.tfplan
